#!/usr/bin/env python
# -*- coding: utf-8 -*-

__all__ = ["make_light_curves"]

import socket


class guard:
    def __init__(*args, **kwargs):
        raise Exception("I told you not to use the Internet!")


socket.socket = guard

import os
import eleanor
from astropy import units as u
from astropy.coordinates import SkyCoord

FMT = "hlsp_eleanor_tess_ffi_tic{0}_s{1:04d}_tess_v1_lc.fits"
crowding_limit = 14.0

def make_light_curves(directory, sector, camera, ccd, **kwargs):
    sector_path = "s{0:04d}".format(sector)
    post_dir = os.path.join(directory, "tess", "postcards", sector_path)
    pm_dir = os.path.join(post_dir, "pointing_model")
    print(pm_dir)
    post_dir = os.path.join(post_dir, "{0}-{1}".format(camera, ccd))
    star = eleanor.Source(
        sector=sector, local=True, post_dir=post_dir, pm_dir=pm_dir, **kwargs
    )
    print(star.pm_dir)
    print(star.pointing)
    star.tess_mag = tess_mag

    if star.tess_mag < crowding_limit:
        crowded_field = False
    else:
        crowded_field = True
    data = eleanor.TargetData(
        star, do_pca=True, do_psf=False, crowded_field = crowded_field
    )  # , height=13, bkg_size=21,)

    tic_id = data.source_info.tic
    tic_id_str = "{0:016d}".format(tic_id)
    lc_dir = os.path.join(
        directory,
        "tess",
        "light_curves",
        sector_path,
        tic_id_str[:4],
        tic_id_str[4:8],
        tic_id_str[8:12],
        tic_id_str[12:14] + "00",
    )

    os.makedirs(lc_dir, exist_ok=True)

    output_fn = FMT.format(tic_id, data.source_info.sector)
    data.save(directory=lc_dir, output_fn=output_fn)


if __name__ == "__main__":
    make_light_curves(
        "/mnt/ceph/users/dforeman/tess/ffis",
        1,
        4,
        1,
        coords=SkyCoord(ra=68.959732, dec=-64.02704, unit=(u.deg, u.deg)),
        tic=38846515,
        gaia=0,
        tess_mag = 10.1
    )
